! open "/users/spacegoing/allsymlinks/macanu/honorsprojects/proposal/pami/pami-gould-12.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/pami14-linEnvLearn.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/Future/2013ECAP0066.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/Future/A Framework for Efficient Structured Max-Margin Learning of High-Order MRF Models.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/Future/Efficient Structured Max-Margin Learning of High-Order MRF Models.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/Future/Exploring Compositional High Order Pattern Potentials for Structured Output Learning.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/Graph-Cut/Gould-PAMI-13.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/Graph-Cut/Gould-PAMI-23.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/Graph-Cut/PBO-Slides.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/LatentSVM/cccp-NIPS03.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/LatentSVM/Latentssvm-ICML09.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/LatentSVM/LatentSVM2008.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/LatentSVM/Referenced by these/chunNam-experi-motif-19.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/LatentSVM/Referenced by these/intro-latentposition-25.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/LatentSVM/Referenced by these/latentSVMTextbook-172.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/LatentSVM/Referenced by these/multiclass-latent-svm-3.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/MaxMargin/Gould-PAMI-36-MaxMargin.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/MaxMargin/Gould-PAMI37-MaxMargin.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/MaxMargin/Gould-PAMI38-MaxMargin.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/MaxMargin/Gould-PAMI39-SVMLatent.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/MaxMargin/KernelDependencyEstimation.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/MaxMargin/MaxMargin_Thesis.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/MaxMargin/Multi-Class SVMs.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/MaxMargin/PAMI-Gould-16.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/MaxMargin/PAMI-Gould-35.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/MISC/37 copy.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/MISC/kClassesSVMs.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/MISC/lecture12.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/MRF/MRF-Survey.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/MRF/PAMI-Gould-17.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/MRF/PAMI-Gould-19.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/Referenced by these/1lineIntro-13.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/Referenced by these/1relatedwork-gould-Kohli.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/Referenced by these/Intro&rela-gould-submodular.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/Referenced by these/None.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/Referenced by these/Relatedwork2places-gould-auxiliary.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/Referenced by these/高阶马尔科夫随机场及其在场景理解中的应用.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/Referenced by these/referenced by these (1relatedwork-gould)/intro-Pletscher.pdf"
! open "/Users/spacegoing/AllSymlinks/macANU/honorsProjects/Proposal/PAMI/Referenced by these/referenced by these (1relatedwork-gould)/related-Pletscher-13.pdf"
